using System.Collections.ObjectModel;

namespace CatCore.Models.Shared
{
	public interface IChatMessage<out TMessage, out TChannel>
		where TMessage : IChatMessage<TMessage, TChannel>
		where TChannel : IChatChannel<TChannel, TMessage>
	{
		/// <summary>
		/// The internal identifier for this chat message
		/// </summary>
		string Id { get; }

		/// <summary>
		/// True if this message was generated by the underlying chat service, and not by another user.
		/// </summary>
		bool IsSystemMessage { get; }

		/// <summary>
		/// True if the message is a /me message, or whatever the equivalent is on the current chat service.
		/// </summary>
		bool IsActionMessage { get; }

		/// <summary>
		/// True if the logged in user was mentioned/tagged/pinged in this message.
		/// </summary>
		bool IsMentioned { get; }

		/// <summary>
		/// The exact message the user sent into the chat, *with* any custom formatting applied by the chat service.
		/// </summary>
		string Message { get; }

		/// <summary>
		/// The user who sent this message
		/// </summary>
		IChatUser Sender { get; }

		/// <summary>
		/// The channel this message was sent in
		/// </summary>
		TChannel Channel { get; }

		/// <summary>
		/// The emotes that are contained in this message.
		/// </summary>
		ReadOnlyCollection<IChatEmote> Emotes { get; }

		/// <summary>
		/// All the raw metadata associated with this message. This contains platform-specific data for devs who want to access any extra data that may not have been parsed.
		/// </summary>
		ReadOnlyDictionary<string, string>? Metadata { get; }
	}
}