name: Build CatCore

on:
  push:
    branches: [ main ]
    paths:
      - 'CatCore/**'
      - '.github/workflows/main.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'CatCore/**'
      - '.github/workflows/main.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.201
    - name: Removed .example suffix from Constants implemenation
      run: find ~ -type f -name Constants.user.cs.example -execdir mv Constants.user.cs.example Constants.user.cs \;
    - name: Find and Replace - Insert Twitch Client Id
      run: find ~ -type f -name Constants.user.cs -exec sed -i ''s/ {{ TWITCH_CLIENT_ID }} /${{ secrets.TWITCH_CLIENT_ID }}/g'' {} \;
    - name: Find and Replace - Insert Twitch Client Secret
      run: find ~ -type f -name Constants.user.cs -exec sed -i ''s/ {{ TWITCH_CLIENT_SECRET }} /${{ secrets.TWITCH_CLIENT_SECRET }}/g'' {} \;
    - name: Build
      id: Build
      run: dotnet build --configuration Release
    - name: Echo Filename
      run: echo $BUILDTEXT \($ASSEMBLYNAME\)
      env:
        BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
        ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.Build.outputs.filename }}
        path: ${{ steps.Build.outputs.artifactpath }}