name: Build CatCore

on:
    workflow_dispatch:
    push:
        branches: [ main ]
        paths:
            - 'CatCore*/**'
            - '.github/workflows/main.yml'
    pull_request:
        branches: [ main ]
        paths:
            - 'CatCore*/**'
            - '.github/workflows/main.yml'

jobs:
    catcore-shared:
        name: CatCore.Shared
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup dotnet
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: 6.0.x
            -   name: Build CatCore.Shared
                id: Build
                run: dotnet build CatCore.Shared --configuration Release
    catcore:
        name: CatCore
        runs-on: ubuntu-latest
        needs: catcore-shared
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup dotnet
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: 6.0.x
            -   name: Removed .example suffix from Constants implementation
                run: find ~ -type f -name Constants.user.cs.example -execdir mv Constants.user.cs.example Constants.user.cs \;
            -   name: Find and Replace - Insert CatCore Auth Server URI
                run: find ~ -type f -name Constants.user.cs -exec sed -i 's| {{ CATCORE_AUTH_SERVER_URI }} |${{ secrets.CATCORE_AUTH_SERVER_URI }}|' {} \;
            -   name: Find and Replace - Insert Twitch Client Id
                run: find ~ -type f -name Constants.user.cs -exec sed -i 's| {{ TWITCH_CLIENT_ID }} |${{ secrets.TWITCH_CLIENT_ID }}|' {} \;
            -   name: Build
                id: Build
                run: dotnet build CatCore --configuration Release
            -   name: Echo Filename
                run: echo $BUILDTEXT \($ASSEMBLYNAME\)
                env:
                    BUILDTEXT: Filename=${{ steps.Build.outputs.filename }}
                    ASSEMBLYNAME: AssemblyName=${{ steps.Build.outputs.assemblyname }}
            -   name: Upload Artifact
                uses: actions/upload-artifact@v1
                with:
                    name: ${{ steps.Build.outputs.filename }}
                    path: ${{ steps.Build.outputs.artifactpath }}
    catcore-azure:
        name: CatCore.Azure
        runs-on: ubuntu-latest
        needs: catcore-shared
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup dotnet
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: 6.0.x
            -   name: Build CatCore.Azure
                id: Build
                run: dotnet build CatCore.Azure --configuration Release